schema_version = "1.0.0"

id = "nd"
version = "1.48.0"
name = "ND"
tagline = "Non-Destructive Modeling Toolkit"
maintainer = "HugeMenace <hello@hugemenace.co>"
type = "add-on"

website = "https://docs.nd.hugemenace.co/"

tags = ["3D View", "Lighting", "Material", "Modeling", "Mesh", "Object", "Scene", "UV"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2024 Tristan S. & Ian J.",
  "2024 HugeMenace",
]

[permissions]
files = "Import built-in and custom assets"
