# “Commons Clause” License Condition v1.0
# 
# See LICENSE for license details. If you did not receive a copy of the license,
# it may be obtained at https://github.com/hugemenace/nd/blob/main/LICENSE.
# 
# Software: ND Blender Addon
# License: MIT
# Licensor: T.S. & I.J. (HugeMenace)

overlay_keys_enum = [
    ("A", "A", ""),
    ("B", "B", ""),
    ("C", "C", ""),
    ("D", "D", ""),
    ("E", "E", ""),
    ("F", "F", ""),
    ("G", "G", ""),
    ("H", "H", ""),
    ("I", "I", ""),
    ("J", "J", ""),
    ("K", "K", ""),
    ("L", "L", ""),
    ("M", "M", ""),
    ("N", "N", ""),
    ("O", "O", ""),
    ("P", "P", ""),
    ("Q", "Q", ""),
    ("R", "R", ""),
    ("S", "S", ""),
    ("T", "T", ""),
    ("U", "U", ""),
    ("V", "V", ""),
    ("W", "W", ""),
    ("X", "X", ""),
    ("Y", "Y", ""),
    ("Z", "Z", ""),
    ("SEMI_COLON", ";", ""),
    ("COMMA", ",", ""),
    ("QUOTE", "“", ""),
    ("ACCENT_GRAVE", "`", ""),
    ("SLASH", "/", ""),
    ("BACK_SLASH", "\\", ""),
    ("LEFT_BRACKET", "[", ""),
    ("RIGHT_BRACKET", "]", ""),
    ("F1", "F1", ""),
    ("F2", "F2", ""),
    ("F3", "F3", ""),
    ("F4", "F4", ""),
    ("F5", "F5", ""),
    ("F6", "F6", ""),
    ("F7", "F7", ""),
    ("F8", "F8", ""),
    ("F9", "F9", ""),
    ("F10", "F10", ""),
    ("F11", "F11", ""),
    ("F12", "F12", ""),
    ("F13", "F13", ""),
    ("F14", "F14", ""),
    ("F15", "F15", ""),
    ("F16", "F16", ""),
    ("F17", "F17", ""),
    ("F18", "F18", ""),
    ("F19", "F19", ""),
    ("F20", "F20", ""),
    ("F21", "F21", ""),
    ("F22", "F22", ""),
    ("F23", "F23", ""),
    ("F24", "F24", ""),
    ("PAUSE", "Pause", ""),
    ("INSERT", "Insert", ""),
    ("HOME", "Home", ""),
    ("PAGE_UP", "Page Up", ""),
    ("PAGE_DOWN", "Page Down", ""),
    ("END", "End", ""),
    ("MEDIA_PLAY", "Play/Pause", ""),
    ("MEDIA_STOP", "Stop", ""),
    ("MEDIA_FIRST", "First", ""),
    ("MEDIA_LAST", "Last", ""),
]